var GAME_LEVELS = [
   ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                           o                                     ",
   "                                                     o          xx       xxx                    xxx          ",
   "                                                    xxx         xx        xx                    xxx          ",
   "                                           xxx                  xx        xx                    xxx          ",
   "                                   xxx                          xxx       xx                    xxx          ",
   "                  o        xxx                                  xx        xx                    xxx          ",
   "                  x                                             xx        xx                    xxx          ",
   "                 xxx                                            xx       xxx                    xxx          ",
   "                xxxxx                                           xx        xx                    xxx          ",
   "               xxxxxxx                                          xxo       xx                    xxx          ",
   "              xx     xx                                         xxx       xx                   oxxx            ",
   "             xx       xx                                        xx        xx                   xxxx            ",
   "     @       x         x                                        xx        xx                    xxx            ",
   "xxxxxxx      x         x                                        xx       xxx                   oxxx            ",
   "xxxxxxx      x         x                                        xx        xx                   xxxx            ",
   "xxxxxxx      x         x                                        xxx       xx                    xxx            ",
   "xxxxxxx      x         x                                        xx        xx                   oxxx            ",
   "xxxxxxx      x                                                           xxx                   xxxx          ",
   "xxxxxxx      x    o                                                                             xxx          ",
   "xxxxxxx      x   xxx        o                                                                   xxx        ",
   "xxxxxxx      x         x   xxx       xxx     xxx     xxx       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx         ",
   "xxxxxxx      x!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
   ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                    vv                                        ",
   "                                                                                                              ",
   "                                                                 o                                            ",
   "                                                                xxx                                           ",
   "     @                                                                                                        ",
   " xxxxxxxx    x  o  x                                                                                          ",
   "             x     x                                                                                          ",
   "             x     x                                            xxx                                           ",
   "             x     xx                                                                                         ",
   "             x     x            o                                                      xxx          x         ",
   "             x     x        xxxxxxxxx                                          x       xx==        ox         ",
   "             x     x       xx!!!!!!!x                           xxx           xx!!!!!!!xx          xx         ",
   "             x     x        x!!!!!!!x                                          x!!!!!!!xx     x     x          ",
   "             x     xx       x!!!!!!!x                                   o      x!!!!!!!xx           x         ",
   "             x     x        x!!!!!!!x                                  xxx     x!!!!!!!xxo        ==x          ",
   "             x     x       xxxxxvxxxx                        xxx               x!!!!!!!xxx          x          ",
   "             x                      x                                          x!!!!!!!xx     x     x          ",
   "             x                      x                 xxx                      x!!!!!!!xx==        ox          ",
   "             x                     ox                                          x!!!!!!!xx          xx          ",
   "             xxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxx                              x!!!!!!!xx           x          ",
   "                                                                               xxxxvvxxxx           x         ",
   "                                                                                              o     x          ",
   "                                                                                              x     x          ",
   "                                                                                   o                x         ",
   "                                                                                  xxx=              x         ",
   "                                                                                  !!!!!!!!xxxxxxxxxxx         ",
   "                                                                                                              "],
   ["                                                                                    xxx                       ",
   "                                                                                    |||                       ",
   "                                                                                            xxx               ",
   "                                                                           xxx              |||       x       ",
   "                                                                           |||       o              xxx   o   ",
   "                                                                                                      x   x   ",
   "                                                                                    xxx             o x!!!!!!!",
   "                                                                                                    xxxxxxxxxx",
   "                                                                                            xxx               ",
   "                                                                           xxx                                ",
   "                   xxx          xxx                                                                 o         ",
   "                   |||          |||                               xxx                               x         ",
   "                          o                                                                                   ",
   "                                                                                                              ",
   "                         xxx                              xx                                xxx     x         ",
   "                                                                                            |||               ",
   "                                                o                                                             ",
   "                   xxx         xxx              x     xx                                                      ",
   "                   |||         |||                                                     x                      ",
   "                   |||         |||  xx     x                                                 o                ",
   "                                                                                           xxxx               ",
   "                                                          xx     xx                                           ",
   "             xxxxxx     xxxxxxx    xxxx                                             x                         ",
   "                                                                                                              ",
   "       o                                                         ||                                           ",
   "  xxxxxxxxxxx                                                                  x          x     o             ",
   "  x         x   x  xxx  x   x  xxx  x   xx                                          o           x             ",
   "  x         x!!!x!!!!!!!x!!!x!!!!!!!x o x                 ||                        x                 x       ",
   "  x  @      xxxxxxxxvxxxxxvxxxxxvxxxxxxxx                                                                   o ",
   "  x  x  x                                     xxxxx       xx     xx                                         x ",
   "  x!!x!!x              o                     xx   x                     xxx                                   ",
   "  x!!x!!x                                   xxx   x=         =o         xxx=          =     o     =         =x",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
